---
- name: create a new file 
  hosts: all
  become: yes
  vars:
    - create_user_file: yes
    - user: Ali
  tasks: 
    - name: create file for user
      ansible.builtin.file:
        path: /home/ {{ user }} /myfile
        state: touch
      when: create_user_file
         
