---
- name: create user file
  hosts: all
  become: yes
  vars: 
    user: "{{ ansible_env.USER }}"
  tasks:
    - name: create root file
      ansible.builtin.file:
        path: /tmp/my_file_root
        state: touch

    - name: create user file
      become_user: "{{ user }}"
      ansible.builtin.file:
        path: /tmp/my_file_{{ user }}
        state: touch
                
