---
- name: Deploy static HTML Website
  hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    - name: Update apt cache and install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy Websites files to document root
      ansible.builtin.copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Apply Nginx Template
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site.
      ansible.builtin.file:
         src: /etc/nginx/sites-available/default
         dest: /etc/nginx/sites-enabled/default
         state: link
      notify: Restart Nginx

    - name: allow all access to tcp port 80
      community.general.ufw:
         rule: allow
         port: '80'
         proto: tcp
    
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
         name: nginx
         state: restarted  
       

