---
- name: Install nginx
  hosts: all
  become: yes
  vars: 
    page_title: My Second Landing Page
    page_description: This is my Second Landing page description.
    doc_root: /var/www/mypage

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    
    - name: Make sure new doc root exists.
      ansible.builtin.file:
         path: "{{ doc_root }}"
         state: directory
         mode: '0755'

    - name: Apply Page Template
      ansible.builtin.template:
         src: files/landing-page.html.j2
         dest: "{{ doc_root }}/index.html"

    - name: Replace document root on default Nginx configuration
      ansible.builtin.replace:
         path: /etc/nginx/sites-available/default
         regexp: '(\s+)root /var/www/html; (\s+.*)?$'
         replace: \g<1>root {{ doc_root }}  ; \g<2>
      notify: Restart Nginx

    - name: allow all access to tcp port 80
      community.general.ufw:
         rule: allow
         port: '80'
         proto: tcp
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
         name: nginx
         state: restarted
         

                            

